version: "3.5"

services:
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: .
      dockerfile: ./dockerfiles/frontend.Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:4000
    ports:
      - 3000:3000
    networks:
      - app
    depends_on:
      - backend

  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfiles/backend.Dockerfile
    environment:
      - SERVER_PORT=4000
      - TIMEZONE_OFFSET=3
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    ports:
      - 4000:4000
    networks:
      - database
      - app
    depends_on:
      - postgres
    command: ["start:sync"]

  postgres:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - database

volumes:
  postgres-data:

networks:
  app:
  database: